### ISSUE TITLE
Layer "not ready yet"

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#363]
I uploaded a layer two days ago. The layer looks ok, but GeoNode says it is "not ready yet". Can you please investigate?
![image](https://user-images.githubusercontent.com/64771599/106773812-c6412e80-6641-11eb-900d-b2838b62afbd.png)

**Comment by meomancer** [comment]
this is fixed @ArnaudIGRAC 
the layer is ready, but i think when the layer was uploaded, there was moment that the server down, i'm not sure
we can't investigate because the log for this problem already gone
so my suggestion is we can raise this in future if the error like this ocurred again

**Comment by ArnaudIGRAC** [comment]
OK, thanks!

**Comment by ArnaudIGRAC** [comment]
reopening this issue because it happens again
![image](https://user-images.githubusercontent.com/64771599/107245086-0b44d680-6a2f-11eb-81c2-1ed25bb0a44e.png)

**Comment by meomancer** [comment]
I can reproduce it (also on local)
checking it

**Comment by meomancer** [comment]
This is bug from geonode
This bug occurs on the staging as well

There is fix from geonode for this issue:
https://github.com/GeoNode/geonode/commit/6aedc9bdbc6d24ac463df66fd4eb55e31badcc05

And i checked, there is also releasing version 3.2 of geonode
https://github.com/GeoNode/geonode/commit/4f780ebf2744ada788e4b21782d4e6c53bd60e0f

So we change the geonode version of our geonode to 3.2
Already tested on staging and we can upload layer 
PRs:
https://github.com/kartoza/IGRAC-GGIS/commit/2bf37483012148fa2a2f0738be40112630af33da
https://github.com/kartoza/IGRAC-GGIS/commit/8e1e9b72849c401c2e9172444caaa2b49a1a8099

We are going to release it on friday as version 1.1.1

**Comment by ArnaudIGRAC** [comment]
Ok Irwan, thank you. Shall we hold on with the uploads until Friday?

**Comment by meomancer** [comment]
yes please @ArnaudIGRAC

**Comment by meomancer** [comment]
this fix is deployed @ArnaudIGRAC @seabilwe @NyakudyaA to production
please check it

**Comment by seabilwe** [comment]
Hi @meomancer, these layers still show  "not ready yet"

- https://ggis.un-igrac.org/layers/?limit=5&offset=15
- https://ggis.un-igrac.org/layers/?limit=5&offset=20

**Comment by meomancer** [comment]
hi @seabilwe 
this fix is for new upload
the old upload that is still show "not ready yet", we need to remove it
so please reupload those

i will remove that layers on admin side

**Comment by meomancer** [comment]
Done @seabilwe 
please reupload those layers

**Comment by ArnaudIGRAC** [comment]
sorry I hadn't noted the pending task:

> please reupload those layers
> CC @ArnaudIGRAC @seabilwe @NyakudyaA

**Comment by ArnaudIGRAC** [comment]
Still two layers pending
![image](https://user-images.githubusercontent.com/64771599/108854917-b1284180-75e8-11eb-9423-6df6f9357394.png)

**Comment by meomancer** [comment]
Done @ArnaudIGRAC

**Comment by ArnaudIGRAC** [comment]
Now the "total drilling depth" and "borehole yields" layers have disappeared. Can you please restore them?

**Comment by meomancer** [comment]
Hi @seabilwe 
Could you please check this? Thank you
I think, we need to reupload it because these layers was uploaded using old geonode that broken

**Comment by seabilwe** [comment]
> Hi @seabilwe
> Could you please check this? Thank you
> I think, we need to reupload it because these layers was uploaded using old geonode that broken

On it @meomancer

**Comment by seabilwe** [comment]
@meomancer @ArnaudIGRAC , the layers are rendering 

![image](https://user-images.githubusercontent.com/56301949/108979389-454ee300-7693-11eb-9d27-871d4336fdc4.png)
![image](https://user-images.githubusercontent.com/56301949/108979511-66afcf00-7693-11eb-89aa-b5c851ff5750.png)

**Comment by ArnaudIGRAC** [comment]
thank you
