### ISSUE TITLE
problems with layer uploads

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#402]
Our colleagues keep on having issues with layer uploads
They managed to upload one layer but it says "Layer not ready yet. Still finalizing layer ingestion..."
https://ggis.un-igrac.org/layers/:geonode:EXP_C45_2021_fs20_Sk_blank_rc

We have had that issue in the past but I thought it had been solved cfr https://github.com/kartoza/IGRAC-GGIS/issues/363

**Comment by meomancer** [comment]
this is fixed, currently the layer is ready, we can just make the layer as "ready"
i checked there are bunch uploads that coming, but this is just 1, so it is not consistencce error that it's hard to trace, so make layer as ready is quick solution for now

**Comment by ArnaudIGRAC** [comment]
good, the layer is now ready in the system. Any idea why we get this message "Layer not ready yet. Still finalizing layer ingestion..."?

**Comment by ArnaudIGRAC** [comment]
This issue is still appearing, can we solve it once for all?
![image](https://user-images.githubusercontent.com/64771599/112321902-bb556280-8cb0-11eb-8630-de8585e7809a.png)

**Comment by ArnaudIGRAC** [comment]
This is becoming urgent, we have had that issue for 2 months already.

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
this is deployment error (it happened when server was down)
could you reupload?

**Comment by ArnaudIGRAC** [comment]
But I uploaded these last layers yesterday, was the server down again?

**Comment by meomancer** [comment]
I'm not sure @ArnaudIGRAC 
is there any statistic that we can check the server status @lucernae ?
so basically arnaud uploaded layer yesterday that the config changed
but on 23rd, it was working fine
