### ISSUE TITLE
Cross-Origin Resource Sharing (CORS) issue?

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#471]
Dear colleagues, some of the layers of the GGIS are used in this application of FAO: https://data.apps.fao.org/aquamaps/ Colleagues from FAO reported that the layers are no longer accessible. I tried myself to import the layers in their application, using https://ggis.un-igrac.org/geoserver/wms?REQUEST=GetCapabilities
I received the following error message:

> Group is not available
An error occurred while invoking GetCapabilities on the WMS server.
If you entered the link manually, please verify that the link is correct.
This error may also indicate that the server does not support CORS. If this is your server, verify that CORS is enabled and enable it if it is not. If you do not control the server, please contact the administrator of the server and ask them to enable CORS. Or, contact the 'FAO AQUAMAPS' Map team by emailing fao-data@fao.org. and ask us to add this server to the list of non-CORS-supporting servers that may be proxied by 'FAO AQUAMAPS' itself.
If you did not enter this link manually, this error may indicate that the group you opened is temporarily unavailable or there is a problem with your internet connection. Try opening the group again, and if the problem persists, please report it by sending an email to fao-data@fao.org..

Can you please investigate this issue?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
What layers is it?
It seems i can't see igrac layer in the link https://data.apps.fao.org/aquamaps/

**Comment by ArnaudIGRAC** [comment]
hi Irwan, those are the 3 layers
https://ggis.un-igrac.org/layers/?limit=5&offset=0&title__icontains=quantitative&abstract__icontains=quantitative&purpose__icontains=quantitative&f_method=or

**Comment by NyakudyaA** [comment]
> hi Irwan, those are the 3 layers https://ggis.un-igrac.org/layers/?limit=5&offset=0&title__icontains=quantitative&abstract__icontains=quantitative&purpose__icontains=quantitative&f_method=or

@lucernae cc @meomancer We need to enable cors in GeoServer. 
* Login to the GeoServer container `/geoserver/webapps/geoserver/WEB-INF/web.xml`
* Edit the file to add the following declaration
```
  <filter>
          <filter-name>cross-origin</filter-name>
          <filter-class>org.eclipse.jetty.servlets.CrossOriginFilter</filter-class>
      </filter>
<filter-mapping>
        <filter-name>cross-origin</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>
```
* Restart geoserver.

The problem is that each restart of GeoServer will result in overwriting the `web.xml`. I suggest updating the entrypoint so that it copies this file into the proper path or mount the file as a config.

After restarting GeoServer you should run the following
```
   curl -v -H "Origin: http://example.com" https://ggis.un-igrac.org/geoserver/wms?REQUEST=GetLegendGraphic&VERSION=1.0.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=tbamap2015:gwb_2019_austria
 ```
Your results should contain the following
```
< HTTP/1.1 200 OK 
< Access-Control-Allow-Origin: http://example.com 
< Access-Control-Allow-Credentials: true 
< Access-Control-Expose-Headers:  
```

**Comment by lucernae** [comment]
Done and deployed using config map mount. Please kindly check @NyakudyaA @meomancer using the original use case. I already test the curl command and it works.

**Comment by NyakudyaA** [comment]
@ArnaudIGRAC Can you try again?

**Comment by ArnaudIGRAC** [comment]
Hi Admire, I tried again but it still doesn't work. Here is the original report I received from our colleagues at FAO

> I am writing to you as we are experiencing again problems with the visualization of layers coming from IGRAC server. It seems now that as data.apps.fao.org we are prevented to connect to your server, while the same request works on localhost.

**Comment by NyakudyaA** [comment]
@ArnaudIGRAC Are you available for a quick google meet to check how you are testing this and we can debug

**Comment by ArnaudIGRAC** [comment]
https://meet.google.com/rdu-skqq-eym

**Comment by NyakudyaA** [comment]
@ArnaudIGRAC I think the error is being generated from the application side, not from our instance. I have done some additional testing here https://www.test-cors.org/# and you can see the response also validates

![errors](https://user-images.githubusercontent.com/2510900/151796731-501bcd59-ebd0-491b-bc9e-b0fd5410ba8d.png)

The error on there looks like something that could be fixed on their side https://stackoverflow.com/questions/12552074/xml-parsing-error-syntax-error-line-number-1-column-1-in-jquery-ajax

**Comment by NyakudyaA** [comment]
@meomancer Can we add the following jar to geoserver: https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-servlets/11.0.7/jetty-servlets-11.0.7.jar into `/geoserver/webapps/geoserver/WEB-INF/lib` and then adjust the config map that was created by Rizky to be
```
<filter>
    <filter-name>cross-origin</filter-name>
    <filter-class>org.eclipse.jetty.servlets.CrossOriginFilter</filter-class>
    <init-param>
        <param-name>allowedOrigins</param-name>
        <param-value>*</param-value>
    </init-param>
    <init-param>
        <param-name>allowedMethods</param-name>
        <param-value>GET,POST,HEAD</param-value>
    </init-param>
    <init-param>
        <param-name>allowedHeaders</param-name>
        <param-value>X-Requested-With,Content-Type,Accept,Origin</param-value>
    </init-param>
</filter>
<filter-mapping>
    <filter-name>cross-origin</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>
```
Then restart GeoServer.

**Comment by ArnaudIGRAC** [comment]
@NyakudyaA Irwan told me he is busy until the end of February, he might not be able to help us with this issue. How shall we proceed?

**Comment by NyakudyaA** [comment]
> @NyakudyaA Irwan told me he is busy until the end of February, he might not be able to help us with this issue. How shall we proceed?

@ArnaudIGRAC I provided the fix in this ticket, I am going to collaborate with our DevOps to implement it. I will ping you within the next hour

**Comment by ArnaudIGRAC** [comment]
Any update on this issue?

**Comment by NyakudyaA** [comment]
> Any update on this issue?

I have updated the server to activate CORS but the response still do not include them. @meomancer will take a look just in case I am missing something

**Comment by ArnaudIGRAC** [comment]
> > Any update on this issue?
> 
> I have updated the server to activate CORS but the response still do not include them. @meomancer will take a look just in case I am missing something

Good, it would be good if we could close the investigation today so I can revert back to our colleagues at FAO. 

I noticed that the platform of FAO rejects all wms from geonode instances (I tried several). Are you aware of a recent update of Geonode or Geoserver which might explain this bug?

**Comment by NyakudyaA** [comment]
> > > Any update on this issue?
> > 
> > 
> > I have updated the server to activate CORS but the response still do not include them. @meomancer will take a look just in case I am missing something
> 
> Good, it would be good if we could close the investigation today so I can revert back to our colleagues at FAO.
> 
> I noticed that the platform of FAO rejects all wms from geonode instances (I tried several). Are you aware of a recent update of Geonode or Geoserver which might explain this bug?

It's not a bug @ArnaudIGRAC. Most GeoNode instances are setup with a basic GeoServer. It's up to the administrator of GeoServer to setup CORS access https://docs.geoserver.org/latest/en/user/production/container.html#enable-cors. In most cases the GeoServer that is powering GeoNode is running through jetty rather than tomcat. Tomcat has a different way to implement CORS on the server.

**Comment by ArnaudIGRAC** [comment]
Dear colleagues, our colleagues from FAO still have issues fetching layers from the GGIS. Here is their description of the issue, can you please investigate?

_We are having fetching data using the previously provided URL by you ([https://ggis.un-igrac.org/geoserver/wms?REQUEST=GetCapabilities](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fggis.un-igrac.org%2Fgeoserver%2Fwms%3FREQUEST%3DGetCapabilities&data=05%7C01%7Carnaud.sterckx%40un-igrac.org%7Cd31071bc30f140f0b42f08dac872a048%7Cb5548d62fed6474c8f5f7368fb7e52bc%7C0%7C0%7C638042691913216207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dMiVeE0leqeWWGMZG4O39QVRQdRKys22Urc7xTI5QNg%3D&reserved=0)).
We are getting a 500 Error when trying to fetch the data from just two web addresses, namely: [http://data.apps.fao.org](https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdata.apps.fao.org%2F&data=05%7C01%7Carnaud.sterckx%40un-igrac.org%7Cd31071bc30f140f0b42f08dac872a048%7Cb5548d62fed6474c8f5f7368fb7e52bc%7C0%7C0%7C638042691913216207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QHpDaaWANaeHInrWeQ8F80wBFqFH0BuoXmVvKsEBLTE%3D&reserved=0) and [http://data.review.fao.org](https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fdata.review.fao.org%2F&data=05%7C01%7Carnaud.sterckx%40un-igrac.org%7Cd31071bc30f140f0b42f08dac872a048%7Cb5548d62fed6474c8f5f7368fb7e52bc%7C0%7C0%7C638042691913216207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=k3JRtfkgGHAVyTS4D5Scbc1bzotM6KRDA8UoFbnl6%2Bw%3D&reserved=0) . We are able to fetch the data from any other domain, even localhost, with no issue.
Which lead us to suspect that there could be some service/protocol that potentially is blocking requests from the aforementioned addresses._

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
How do they access it? 
I can access the url https://ggis.un-igrac.org/geoserver/wms?REQUEST=GetCapabilities

Maybe the server was down, could you ask them to retry?

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, the server was not down, it is a long-lasting issue. I still don't understand if the issue is on our side or their side. Our wms service works just fine in any other platform except theirs. When I try to connect on their platform I receive this error message: 
Group is not available
An error occurred while invoking GetCapabilities on the WMS server.

If you entered the link manually, please verify that the link is correct.

This error may also indicate that the server does not support [CORS](http://enable-cors.org/). If this is your server, verify that CORS is enabled and enable it if it is not. If you do not control the server, please contact the administrator of the server and ask them to enable CORS. Or, contact the 'FAO Hand-in-Hand' Map team by emailing [fao-data@fao.org](mailto:fao-data@fao.org). and ask us to add this server to the list of non-CORS-supporting servers that may be proxied by 'FAO Hand-in-Hand' itself.

If you did not enter this link manually, this error may indicate that the group you opened is temporarily unavailable or there is a problem with your internet connection. Try opening the group again, and if the problem persists, please report it by sending an email to [fao-data@fao.org](mailto:fao-data@fao.org)..

**Comment by ArnaudIGRAC** [comment]
I tried other WMS services and none of them is working, so I suspect the issue is on their side. What do you think?

**Comment by meomancer** [comment]
I'm not sure @ArnaudIGRAC 
I tried to import using my local geonode and also my qgis, and they are working just fine
![Selection_018](https://user-images.githubusercontent.com/4530905/203027084-7848a77f-c7b5-447d-b655-b8d9a1e306ae.png)

Maybe their service is not compatible with our wms?
> the error is '_Group is not available'

Hi @NyakudyaA  Could you give us insight?

**Comment by NyakudyaA** [comment]
This issue is from their side. I suggest they fix their code to allow normal passing of WMS get capabilities documents.
![ows](https://user-images.githubusercontent.com/2510900/203486407-d5e8208c-6b5c-4ece-9cf2-4b1a3196f0d1.png)

If you look at the screenshot above it shows two main errors
1) The URL is incorrectly flagged as a ArcGIS Feature Service while it's just a simple OGC WMS request
2) They proxy the getcapabilities request through their own implementation and it fails to parse the XML returned.

**Comment by ArnaudIGRAC** [comment]
Thank you both, I forwarded your answer to our partners
