### ISSUE TITLE
attribute window do not show properly

### ISSUE THREAD

**Issue by ArnaudIGRAC** [kartoza/IGRAC-GGIS#562]
This is not how the attribute windows looked like in the previous version
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/ba425659-7f4e-43f5-ac0f-b8a67634b624)

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
What layer is it?
It is working fine on https://ggis.un-igrac.org/catalogue/#/dataset/1810

**Comment by ArnaudIGRAC** [comment]
you are right Irwan, the issue is with the slug maps that are available on the front page of the GGIS

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
I have fixed this, could you check it?

**Comment by ArnaudIGRAC** [comment]
hi Irwan, there is still an issue with the attribute names, which are not the ones we assigned to the layer
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/9454456a-e49c-4974-a677-7a2ff0faf530)
![image](https://github.com/kartoza/IGRAC-GGIS/assets/64771599/05674bdb-3ac0-4a92-8769-9edb230ca39c)

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
Fixed, could you check it?

**Comment by ArnaudIGRAC** [comment]
Not working for other viewers...
https://ggis.un-igrac.org/view/tba/
https://ggis.un-igrac.org/view/twap/

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, any update on this issue?

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
I have update https://ggis.un-igrac.org/view/twap/ also
Please check it

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, thank you. There are still other viewers with that problem (see e.g. https://ggis.un-igrac.org/view/sids/). Please check all map viewers.
Moreover, if you change the dataset attributes of a layer it will not be updated in the map viewer.

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
That is the logic on geonode, the config between layer is different with map
Maybe i need to ask in geonode how to sync it

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
After i checked, it should be automatically update
When we change the attributes on layer, on the map it will also changed
I will check it tomorrow

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, it seems to be working fine now. Have you checked on your side?

**Comment by ArnaudIGRAC** [comment]
Coming back to what I said, the attribute tables seem to be ok but the synchronization between maps and slug maps doesn't work. I just edited https://ggis.un-igrac.org/catalogue/#/map/2248, but my edits don't appear on https://ggis.un-igrac.org/view/basm/

**Comment by ArnaudIGRAC** [comment]
Any update here?

**Comment by meomancer** [comment]
hi @ArnaudIGRAC 
the slug map for : https://ggis.un-igrac.org/view/basm/ is using https://ggis.un-igrac.org/catalogue/#/detail/map/1471

There are 2 maps that using same name
https://ggis.un-igrac.org/catalogue/#/search/?q=Senegalo-Mauritanian%20Aqu&f=map

**Comment by ArnaudIGRAC** [comment]
Thank you Irwan! I didn't notice we had duplicated maps, I have just deleted the old one.
