### ISSUE TITLE
Wagtail styling

### ISSUE THREAD

**Issue by seabilwe** [kartoza/IGRAC-GGIS#584]
Ticket sent through Support portal: https://kartoza.com/app/issue/ISS-2023-00028

I am currently editing the About section, in Wagtail. There are 2 things I would like to change:

- the fonts of the headers. H2 is smaller than H3, which is already quite small. Please use the same fonts as in the website, as specified in visualstyleguide.pdf https://github.com/kartoza/IGRAC-GGIS/blob/develop/documents/design/visualstyleguide.pdf
- I can't enter an empty line. That is, several consecutive line breaks will always appear as one simple line break. Empty lines would be useful to better structure the text, make it lighter to read.

Ticket Priority: Medium

**Comment by ArnaudIGRAC** [comment]
Any update on this please?

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
I'm sorry, i will work on it tomorrow

**Comment by meomancer** [comment]
Hi @ArnaudIGRAC 
This is fixed and released

**Comment by ArnaudIGRAC** [comment]
Hi Irwan, I don't see any difference. I am still unable to insert multiple break lines
